# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.1.x
    performMultiLevelLookup: true

- script: dotnet build -c Release
  displayName: 'Build'

- script: dotnet test
  displayName: 'Test'

- script: |
    mkdir -p out/MiscTwitchApi
    mkdir -p out/TwitchChatBot
    dotnet publish
    cp -r MiscTwitchChat/bin/*/*/publish/* out/MiscTwitchApi
    cp -r TwitchActivityBot/bin/*/*/publish/* out/TwitchChatBot
  displayName: 'Publish'

- script: |
    mkdir packages
    zip -r packages/MiscTwitchApi.zip out/MiscTwitchApi/*
    zip -r packages/TwitchActivityBot.zip out/TwitchChatBot/*
  displayName: 'Package'

- publish: $(System.DefaultWorkingDirectory)/packages/
  artifact: drop
  displayName: 'Upload API'