volumes:
  mariadb-volume:

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=twitchapi
    volumes:
      - mariadb-volume:/var/lib/mysql